name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libcriterion-dev
        sudo apt-get install lcov
        sudo apt-get install gcovr
    - name: Run tests
      run: |
        make tests_run
        lcov --capture --directory . --output-file coverage.info --no-external --exclude '.*main\.c' --exclude '${{ github.workspace }}/tests/*' --exclude build/
    - name: Display coverage report
      run: |
        cat coverage.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
